### ISSUE TITLE
TranslateViewHelper throws ValueError if strings contain '%'

### ISSUE THREAD

**Issue by Leoniebra** [phantasie-schmiede/psb-foundation#6] opened 2022-12-12 12:55 UTC
Passing a string "10%Mathe" to psb:translate threw a valueError when calling the vsprintf method in line 89 of the TranslateViewHelper. This is expected behavior from the vsprintf method, as % is the operative character for declaring conversion directives: https://www.php.net/manual/en/function.vsprintf.php

**Comment by phantasie-schmiede** [comment] 2023-01-09 10:57
The problem is caused by double processing of the localization string with vsprintf and sprintf. The latter function is already executed inside the translate function of extbase. The solution is to execute vsprintf in TranslateViewHelper only if the value after the translate function is null.

Fixed with release 1.2.4 (#8).

**Closed as completed by phantasie-schmiede** 2023-01-09 10:57 UTC
